#!/usr/bin/env ruby

require 'strelka'

# An application that demonstrates the 'authtoken' auth provider for Strelka apps.
class AuthTokenDemo < Strelka::App

	# The Strelka appid
	ID = 'authtoken-demo'


	# Auth plugin
	plugin :auth
	auth_provider :authtoken
	require_auth_for '/restricted'


	# Templating plugin
	plugin :templating
	layout 'authtoken/layout.tmpl'
	templates form: 'authtoken/form.tmpl',
	          success: 'authtoken/success.tmpl'


	# Routing plugin
	plugin :routing
	get do |req|
		return :form
	end

	get 'restricted' do |req|
		return :success
	end

end # class AuthTokenDemo

AuthTokenDemo.run if $0 == __FILE__

